version: '3.6'

volumes:
  rabbitmq_data:
    driver: local

services:
  # Rabbit MQ Stomp
  rabbitmq_stomp:
    image: activiti/rabbitmq-stomp
    container_name: rabbitmq-stomp
    volumes:
      - 'rabbitmq_data:/var/lib/rabbitmq'
    ports:
      - '8081:15672'
      - '61613:61613'
    


  
      
      