spring:
    data:
        mongodb:
            database: messages
            host: localhost
            port: 27017
            username: devroot
            password: devroot

## Spring Open API
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

logging.level:
    com.dreamsoftware.websocketclient: DEBUG
    org.springframework.web.socket: DEBUG

server.port: 8086