stomp:
    prefix: /topic
    host: localhost
    port: 61613
    client:
        username: guest
        passcode: guest

logging.level:
    com.dreamsoftware.websocketserver: DEBUG
    org.springframework.web.socket: DEBUG

server.port: 8080