

stomp:
    prefix: /topic
    host: localhost
    port: 61613
    client:
        username: guest
        passcode: guest

## Spring Open API
springdoc:
    swagger-ui:
        path: /swagger-ui.html
    api-docs:
        path: /api-docs

logging.level:
    com.dreamsoftware.websocketserver: DEBUG
    org.springframework.web.socket: DEBUG

server.port: 8080